# Generated by Django 3.2.9 on 2022-01-14 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsmodel',
            name='post',
        ),
    ]
