# Generated by Django 3.2.9 on 2022-01-17 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_work', '0002_remove_commentsmodel_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsmodel',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='backend_work.postmodel'),
            preserve_default=False,
        ),
    ]
